-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgq52Vl1n+088FoG36
1xvRG6tv92Eb+lQOVTPBNKUSLRigCgYIKoZIzj0DAQehRANCAAQss3AYVF9LtmeL
clZEFTrnulF+k04pj8+aMnKNmNidEY2VmkxboyXL+dsJi9NJF8wmxadkSPwjbkYO
KHZdqmlR
-----END PRIVATE KEY-----