name: Todorant Workflows
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Compile code
        run: yarn tsc --skibLibCheck
      - name: create env file
        run: |
          touch .env
          echo JWT=TEST >> .env
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint
