name: Todorant Workflows
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Compile code
        run: yarn tsc --skipLibCheck
      - name: create env file
        run: |
          touch .env
          echo JWT=TEST >> .env
      - name: create testing google credentials
        run: |
          mkdir assets
          touch assets/api-4987639842126744234-562450-67105810381f.json
          echo "{\"client_email\": \"test\", \"private_key\": \"test\"}" >> assets/api-4987639842126744234-562450-67105810381f.json
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint
